// Core data loading + owner mapping, ported from helpers.R / fetch_data.R.
// All league data is static JSON generated by scripts/convert_data.py.

import standingsJson from "@/data/standings.json";
import scheduleJson from "@/data/schedule.json";
import draftsJson from "@/data/drafts.json";
import startersJson from "@/data/starters.json";
import headshotsJson from "@/data/headshots.json";

type Columnar = { columns: string[]; rows: (string | number | null)[][] };

function toObjects<T>(data: Columnar): T[] {
  const { columns, rows } = data;
  return rows.map((row) => {
    const obj: Record<string, unknown> = {};
    columns.forEach((c, i) => (obj[c] = row[i]));
    return obj as T;
  });
}

export interface StandingRow {
  season: number;
  franchise_id: number;
  franchise_name: string;
  league_rank: number;
  h2h_wins: number;
  h2h_losses: number;
  h2h_ties: number | null;
  h2h_winpct: number;
  points_for: number;
  points_against: number;
  allplay_wins: number | null;
  allplay_losses: number | null;
  allplay_winpct: number | null;
  owner: string;
}

export interface ScheduleRow {
  season: number;
  week: number;
  franchise_id: number;
  franchise_score: number;
  result: "W" | "L" | "T" | null;
  opponent_id: number;
  opponent_score: number;
  game_type: "Regular Season" | "Playoffs";
  team_owner: string;
  opponent_owner: string;
}

export interface DraftRow {
  season: number;
  round: number;
  pick: number;
  overall: number;
  franchise_id: number;
  franchise_name: string;
  user_nickname: string;
  player_id: number;
  player_name: string;
  pos: string;
  team: string | null;
  owner: string;
}

export interface StarterRow {
  season: number;
  week: number;
  franchise_id: number;
  franchise_name: string;
  franchise_score: number;
  lineup_slot: string;
  player_score: number | null;
  projected_score: number | null;
  player_id: number;
  player_name: string;
  pos: string;
  team: string | null;
  owner: string;
}

// GFFL owner names mapped by alphabetical index of ESPN user_nickname
// (duplicates = one person with multiple ESPN accounts).
const OWNER_NAMES_BY_INDEX = [
  "Alex", "Connor", "Harry", "Matt", "Connor", "Harry", "Joe",
  "Jack", "Mike", "Kerley", "RJ", "Faz", "Tom",
];

interface RawDraftRow extends Omit<DraftRow, "owner"> {}

function buildOwnerLookup(drafts: RawDraftRow[]): Map<string, string> {
  // nickname -> owner via alphabetical index, same as helpers.R build_owner_map
  const nicknames = [...new Set(drafts.map((d) => d.user_nickname))].sort();
  const lookup = new Map<string, string>();
  nicknames.forEach((nick, i) => {
    lookup.set(nick, OWNER_NAMES_BY_INDEX[i] ?? nick);
  });
  return lookup;
}

// Regular season length changed over the years:
// 2017-2018 weeks 1-13, 2019-2020 weeks 1-14, 2021+ weeks 1-15.
export function classifyGameType(season: number, week: number): "Regular Season" | "Playoffs" {
  if (season <= 2018 && week <= 13) return "Regular Season";
  if ((season === 2019 || season === 2020) && week <= 14) return "Regular Season";
  if (season >= 2021 && week <= 15) return "Regular Season";
  return "Playoffs";
}

interface LeagueData {
  standings: StandingRow[];
  schedule: ScheduleRow[];
  drafts: DraftRow[];
  starters: StarterRow[];
  seasons: number[];
  owners: string[];
  /** season|franchise_id -> owner name */
  ownerByFranchise: Map<string, string>;
}

let cache: LeagueData | null = null;

export function getLeagueData(): LeagueData {
  if (cache) return cache;

  const rawDrafts = toObjects<RawDraftRow>(draftsJson as Columnar);
  const nickToOwner = buildOwnerLookup(rawDrafts);

  // season|franchise_id -> owner (franchises are re-id'd per season)
  const ownerByFranchise = new Map<string, string>();
  const franchiseName = new Map<string, string>();
  for (const d of rawDrafts) {
    const key = `${d.season}|${d.franchise_id}`;
    if (!ownerByFranchise.has(key)) {
      ownerByFranchise.set(key, nickToOwner.get(d.user_nickname) ?? d.franchise_name);
      franchiseName.set(key, d.franchise_name);
    }
  }
  const ownerOf = (season: number, fid: number, fallback: string) =>
    ownerByFranchise.get(`${season}|${fid}`) ?? fallback;

  const drafts: DraftRow[] = rawDrafts.map((d) => ({
    ...d,
    owner: ownerOf(d.season, d.franchise_id, d.franchise_name),
  }));

  const standings: StandingRow[] = toObjects<Omit<StandingRow, "owner">>(
    standingsJson as Columnar
  ).map((s) => ({ ...s, owner: ownerOf(s.season, s.franchise_id, s.franchise_name) }));

  const schedule: ScheduleRow[] = toObjects<
    Omit<ScheduleRow, "game_type" | "team_owner" | "opponent_owner">
  >(scheduleJson as Columnar).map((g) => ({
    ...g,
    game_type: classifyGameType(g.season, g.week),
    team_owner: ownerOf(g.season, g.franchise_id, String(g.franchise_id)),
    opponent_owner: ownerOf(g.season, g.opponent_id, String(g.opponent_id)),
  }));

  const starters: StarterRow[] = toObjects<Omit<StarterRow, "owner">>(
    startersJson as Columnar
  ).map((s) => ({ ...s, owner: ownerOf(s.season, s.franchise_id, s.franchise_name) }));

  const seasons = [...new Set(standings.map((s) => s.season))].sort((a, b) => a - b);
  const owners = [...new Set(standings.map((s) => s.owner))].sort();

  cache = { standings, schedule, drafts, starters, seasons, owners, ownerByFranchise };
  return cache;
}

const headshots = headshotsJson as Record<string, number>;

export function headshotUrl(playerName: string): string | null {
  const id = headshots[playerName.toLowerCase()];
  if (!id) return null;
  return `https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/${id}.png&w=96&h=70&cb=1`;
}

export const BENCH_SLOTS = new Set(["BE", "IR"]);

/**
 * Map an original www/ image reference (e.g. "photos/Alex.jpeg") to its
 * optimized WebP copy in public/ (e.g. "/photos/Alex.webp").
 */
export function photoUrl(ref: string): string {
  const clean = ref.replace(/^\//, "");
  return "/" + clean.replace(/\.(png|jpe?g)$/i, ".webp");
}

export function fmt(n: number, digits = 1): string {
  return n.toLocaleString("en-US", {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  });
}
