// Core data loading + owner mapping, ported from helpers.R / fetch_data.R.
// All league data is static JSON generated by scripts/convert_data.py.

import standingsJson from "@/data/standings.json";
import scheduleJson from "@/data/schedule.json";
import draftsJson from "@/data/drafts.json";
import startersJson from "@/data/starters.json";
import headshotsJson from "@/data/headshots.json";

type Columnar = { columns: string[]; rows: (string | number | null)[][] };

function toObjects<T>(data: Columnar): T[] {
  const { columns, rows } = data;
  return rows.map((row) => {
    const obj: Record<string, unknown> = {};
    columns.forEach((c, i) => (obj[c] = row[i]));
    return obj as T;
  });
}

export interface StandingRow {
  season: number;
  franchise_id: number;
  franchise_name: string;
  league_rank: number;
  h2h_wins: number;
  h2h_losses: number;
  h2h_ties: number | null;
  h2h_winpct: number;
  points_for: number;
  points_against: number;
  allplay_wins: number | null;
  allplay_losses: number | null;
  allplay_winpct: number | null;
  owner: string;
}

export interface ScheduleRow {
  season: number;
  week: number;
  franchise_id: number;
  franchise_score: number;
  result: "W" | "L" | "T" | null;
  opponent_id: number;
  opponent_score: number;
  game_type: "Regular Season" | "Playoffs";
  team_owner: string;
  opponent_owner: string;
}

export interface DraftRow {
  season: number;
  round: number;
  pick: number;
  overall: number;
  franchise_id: number;
  franchise_name: string;
  user_nickname: string;
  player_id: number;
  player_name: string;
  pos: string;
  team: string | null;
  owner: string;
}

export interface StarterRow {
  season: number;
  week: number;
  franchise_id: number;
  franchise_name: string;
  franchise_score: number;
  lineup_slot: string;
  player_score: number | null;
  projected_score: number | null;
  player_id: number;
  player_name: string;
  pos: string;
  team: string | null;
  owner: string;
}

// GFFL owner names pinned per ESPN user_nickname. The original scheme mapped
// nicknames to owners by alphabetical index, which silently scrambles ALL
// owners across every season if a nickname is ever added or renamed on ESPN.
// This dictionary is the verified output of that scheme against 2017-2025
// draft data — do not remove entries; add new accounts as they appear.
const NICKNAME_TO_OWNER: Record<string, string> = {
  "Faz929": "Alex",
  "GenoSmithGOAT": "Connor",
  "HadlockIII": "Harry",
  "MMik55": "Matt",
  "espnfan7035599953": "Connor",
  "hhadlock@optonline.net": "Harry",
  "jvasil6524890": "Joe",
  "metaldeath37": "Jack",
  "mtag93": "Mike",
  "prone2confusion": "Kerley",
  "rjvasi5159015": "RJ",
  "tfasan9991529": "Faz",
  "thomasmikalonis": "Tom",
};

interface RawDraftRow extends Omit<DraftRow, "owner"> {}

function buildOwnerLookup(drafts: RawDraftRow[]): Map<string, string> {
  const lookup = new Map<string, string>();
  for (const d of drafts) {
    if (lookup.has(d.user_nickname)) continue;
    const owner = NICKNAME_TO_OWNER[d.user_nickname];
    if (owner) {
      lookup.set(d.user_nickname, owner);
    } else {
      // Unknown ESPN account: fall back to the raw nickname so history stays
      // intact, and shout at build time so the dictionary gets updated.
      console.warn(
        `[GFFL] Unknown ESPN nickname "${d.user_nickname}" (season ${d.season}). ` +
          `Add it to NICKNAME_TO_OWNER in src/lib/data.ts.`
      );
      lookup.set(d.user_nickname, d.user_nickname);
    }
  }
  return lookup;
}

// Regular season length changed over the years:
// 2017-2018 weeks 1-13, 2019-2020 weeks 1-14, 2021+ weeks 1-15.
export function classifyGameType(season: number, week: number): "Regular Season" | "Playoffs" {
  if (season <= 2018 && week <= 13) return "Regular Season";
  if ((season === 2019 || season === 2020) && week <= 14) return "Regular Season";
  if (season >= 2021 && week <= 15) return "Regular Season";
  return "Playoffs";
}

interface LeagueData {
  standings: StandingRow[];
  schedule: ScheduleRow[];
  drafts: DraftRow[];
  starters: StarterRow[];
  seasons: number[];
  owners: string[];
  /**
   * Seasons whose final standings exist (ESPN publishes league_rank only after
   * the season ends; mid-season every rank is 0). Seasonal awards — champion,
   * sacko, playoff berths, single-season records — must only consider these.
   */
  finalSeasons: Set<number>;
  /** season|franchise_id -> owner name */
  ownerByFranchise: Map<string, string>;
}

let cache: LeagueData | null = null;

export function getLeagueData(): LeagueData {
  if (cache) return cache;

  const rawDrafts = toObjects<RawDraftRow>(draftsJson as Columnar);
  const nickToOwner = buildOwnerLookup(rawDrafts);

  // season|franchise_id -> owner (franchises are re-id'd per season)
  const ownerByFranchise = new Map<string, string>();
  const franchiseName = new Map<string, string>();
  for (const d of rawDrafts) {
    const key = `${d.season}|${d.franchise_id}`;
    if (!ownerByFranchise.has(key)) {
      ownerByFranchise.set(key, nickToOwner.get(d.user_nickname) ?? d.franchise_name);
      franchiseName.set(key, d.franchise_name);
    }
  }
  const ownerOf = (season: number, fid: number, fallback: string) =>
    ownerByFranchise.get(`${season}|${fid}`) ?? fallback;

  const drafts: DraftRow[] = rawDrafts.map((d) => ({
    ...d,
    owner: ownerOf(d.season, d.franchise_id, d.franchise_name),
  }));

  // Only seasons that have draft data carry owner identities. ESPN starts
  // serving standings/schedule for a renewed season weeks before the draft;
  // without draft rows every team would show up as a phantom owner ("1"…"10"),
  // so pre-draft seasons are excluded entirely.
  const draftSeasons = new Set(drafts.map((d) => d.season));

  const rawStandings = toObjects<Omit<StandingRow, "owner">>(
    standingsJson as Columnar
  ).filter((s) => draftSeasons.has(s.season));

  // ESPN's league_rank (rankCalculatedFinal) is 0 for every team until the
  // season is finalized. A rank of 0 would satisfy checks like rank <= 4
  // (playoffs) or rank <= 2 (title game), so mid-season seasons are flagged
  // non-final and their ranks pushed to a harmless sentinel.
  const finalSeasons = new Set<number>();
  for (const season of draftSeasons) {
    const rows = rawStandings.filter((s) => s.season === season);
    if (rows.length > 0 && rows.every((s) => s.league_rank >= 1)) {
      finalSeasons.add(season);
    }
  }

  const standings: StandingRow[] = rawStandings.map((s) => ({
    ...s,
    league_rank: finalSeasons.has(s.season) ? s.league_rank : 999,
    owner: ownerOf(s.season, s.franchise_id, s.franchise_name),
  }));

  const schedule: ScheduleRow[] = toObjects<
    Omit<ScheduleRow, "game_type" | "team_owner" | "opponent_owner">
  >(scheduleJson as Columnar)
    .filter((g) => draftSeasons.has(g.season))
    .map((g) => ({
      ...g,
      game_type: classifyGameType(g.season, g.week),
      team_owner: ownerOf(g.season, g.franchise_id, String(g.franchise_id)),
      opponent_owner: ownerOf(g.season, g.opponent_id, String(g.opponent_id)),
    }));

  const starters: StarterRow[] = toObjects<Omit<StarterRow, "owner">>(
    startersJson as Columnar
  )
    .filter((s) => draftSeasons.has(s.season))
    .map((s) => ({ ...s, owner: ownerOf(s.season, s.franchise_id, s.franchise_name) }));

  const seasons = [...new Set(standings.map((s) => s.season))].sort((a, b) => a - b);
  const owners = [...new Set(standings.map((s) => s.owner))].sort();

  cache = {
    standings, schedule, drafts, starters, seasons, owners, finalSeasons, ownerByFranchise,
  };
  return cache;
}

const headshots = headshotsJson as Record<string, number>;

/**
 * Normalize a player name for headshot lookup: lowercase, no periods,
 * generational suffixes dropped. MUST stay in sync with normalize_name()
 * in scripts/convert_data.py, which builds headshots.json with the same rule.
 */
function normalizeName(name: string): string {
  return name
    .toLowerCase()
    .replace(/\./g, "")
    .replace(/\s+(jr|sr|ii|iii|iv)$/i, "")
    .replace(/\s+/g, " ")
    .trim();
}

export function headshotUrl(playerName: string): string | null {
  const id = headshots[normalizeName(playerName)] ?? headshots[playerName.toLowerCase()];
  if (!id) return null;
  return `https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/${id}.png&w=96&h=70&cb=1`;
}

export const BENCH_SLOTS = new Set(["BE", "IR"]);

/**
 * Map an original www/ image reference (e.g. "photos/Alex.jpeg") to its
 * optimized WebP copy in public/ (e.g. "/photos/Alex.webp").
 */
export function photoUrl(ref: string): string {
  const clean = ref.replace(/^\//, "");
  return "/" + clean.replace(/\.(png|jpe?g)$/i, ".webp");
}

export function fmt(n: number, digits = 1): string {
  return n.toLocaleString("en-US", {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  });
}
