// Replicates the file.exists() lookups against www/photos/ in app.R.
// All original images (any extension/case) were converted to .webp in
// public/photos/, so existence checks reduce to a basename lookup.

export const PHOTO_BASENAMES = new Set<string>([
  "Alex",
  "GFFL",
  "Hunt",
  "Jack",
  "Kerley",
  "RJ",
  "Tom",
  "alex_bust",
  "alex_bust2",
  "alex_headshot",
  "alex_jersey",
  "centurion_trophy",
  "champion_ring",
  "connor_headshot",
  "connor_jersey",
  "faz",
  "faz_bust",
  "faz_bust2",
  "faz_headshot",
  "faz_jersey",
  "frame",
  "harry_headshot",
  "harry_jersey",
  "jack_bust",
  "jack_bust2",
  "jack_headshot",
  "jack_jersey",
  "joe_headshot",
  "joe_jersey",
  "kenny_headshot",
  "kenny_jersey",
  "kerley_bust",
  "kerley_bust2",
  "kerley_headshot",
  "kerley_jersey",
  "lombardi",
  "matt_headshot",
  "matt_jersey",
  "mike_headshot",
  "mike_jersey",
  "mvp",
  "oneseed_2017",
  "oneseed_2018",
  "oneseed_2019",
  "oneseed_2020",
  "oneseed_2021",
  "oneseed_2022",
  "oneseed_2023",
  "oneseed_2024",
  "oneseed_2025",
  "playoffs_2017",
  "playoffs_2018",
  "playoffs_2019",
  "playoffs_2020",
  "playoffs_2021",
  "playoffs_2022",
  "playoffs_2023",
  "playoffs_2024",
  "playoffs_2025",
  "rj_headshot",
  "rj_jersey",
  "sacko",
  "sean_headshot",
  "sean_jersey",
  "tom_bust",
  "tom_bust2",
  "tom_headshot",
  "tom_jersey",
  "xingwei_headshot",
]);

/** Try basename variants in order, return the first that exists (as /photos/x.webp). */
export function findPhoto(...names: string[]): string | null {
  for (const n of names) {
    if (PHOTO_BASENAMES.has(n)) return `/photos/${n}.webp`;
  }
  return null;
}
