# ============================================================
#  defense_profiles.R  (nflmodel)
#
#  The defensive mirror of player_profiles.R (rule R1.12 /
#  Study S14): everything a defense ALLOWS, under the exact
#  definitions of R1.11, at the same three grains — per GAME,
#  per SEASON, and ERA (2021+). Rates recomputed from summed
#  counts at every grain.
#
#  Mirrored definitions:
#   • carries faced = DESIGNED carries only (scrambles excluded);
#     scrambles allowed are tracked separately on the pass side
#   • targets faced = pass attempts with a receiver id;
#     depth bands identical: <0 / 0-4 / 5-9 / 10-19 / 20+
#   • completion% allowed by band; catch%-allowed == comp%-allowed
#     at the defense level (same events seen from one side)
#   • sacks/INTs are GENERATED by the defense; CPOE-allowed is the
#     mean cpoe of throws against
#   • receiver-position splits (RB/WR/TE) use the offense's
#     season roster, same source as the RB-carry denominator
#
#  Outputs (data/defense/, regenerable):
#    def_profile_game.csv.gz   one row per defense-game
#    def_profile_season.csv    one row per defense-season
#    def_profile_era.csv       one row per defense (2021+)
# ============================================================

suppressMessages({ library(dplyr); library(tidyr); library(readr); library(rlang) })

DEF_DIR <- file.path("data", "defense")
DEF_GAME_FILE   <- file.path(DEF_DIR, "def_profile_game.csv.gz")
DEF_SEASON_FILE <- file.path(DEF_DIR, "def_profile_season.csv")
DEF_ERA_FILE    <- file.path(DEF_DIR, "def_profile_era.csv")

build_def_profile_game <- function(seasons) {
  pbp <- .profile_pbp(seasons) %>% filter(!is.na(defteam))

  pos <- load_rosters_cache(seasons, skill_only = FALSE) %>%
    select(season, gsis_id, position)

  # -- rushing allowed (designed carries faced) ---------------
  ru <- pbp %>%
    filter(rush == 1) %>%
    group_by(season, week, game_id, defense = defteam) %>%
    summarise(
      carries_faced = n(), rush_yds_allowed = sum(rushing_yards, na.rm = TRUE),
      rush_td_allowed = sum(rush_touchdown),
      rush_fd_allowed = sum(first_down, na.rm = TRUE),
      rush_epa_allowed = sum(epa, na.rm = TRUE),
      rush_succ_allowed = sum(success, na.rm = TRUE),
      stuffs_made = sum(yards_gained <= 0),
      explosive_rush_allowed = sum(yards_gained >= 10),
      carries_faced_i10 = sum(yardline_100 <= 10),
      carries_faced_i5 = sum(yardline_100 <= 5),
      .groups = "drop")

  # -- receiving allowed (targets faced) ----------------------
  rc_base <- pbp %>%
    filter(pass_attempt == 1, sack == 0, !is.na(receiver_player_id)) %>%
    left_join(pos, by = c("season", "receiver_player_id" = "gsis_id"))
  rc <- rc_base %>%
    group_by(season, week, game_id, defense = defteam) %>%
    summarise(
      targets_faced = n(), rec_allowed = sum(complete_pass),
      rec_yds_allowed = sum(receiving_yards, na.rm = TRUE),
      rec_td_allowed = sum(pass_touchdown),
      air_yds_faced = sum(air_yards, na.rm = TRUE),
      yac_allowed = sum(yards_after_catch, na.rm = TRUE),
      rec_fd_allowed = sum(first_down * complete_pass, na.rm = TRUE),
      rec_epa_allowed = sum(epa, na.rm = TRUE),
      tgt_faced_rz = sum(yardline_100 <= 20),
      tgt_faced_ez = sum(!is.na(air_yards) & air_yards >= yardline_100),
      !!!setNames(lapply(DEPTH_LABS, function(b)
        quo(sum(depth_band == !!b, na.rm = TRUE))),
        paste0("tgt_faced_", DEPTH_LABS)),
      !!!setNames(lapply(DEPTH_LABS, function(b)
        quo(sum(complete_pass[depth_band == !!b], na.rm = TRUE))),
        paste0("rec_allowed_", DEPTH_LABS)),
      # receiver-position splits
      !!!setNames(lapply(c("RB","WR","TE"), function(p)
        quo(sum(position == !!p, na.rm = TRUE))),
        paste0("tgt_faced_", c("rb","wr","te"))),
      !!!setNames(lapply(c("RB","WR","TE"), function(p)
        quo(sum(complete_pass[position == !!p], na.rm = TRUE))),
        paste0("rec_allowed_", c("rb","wr","te"))),
      !!!setNames(lapply(c("RB","WR","TE"), function(p)
        quo(sum(receiving_yards[position == !!p], na.rm = TRUE))),
        paste0("rec_yds_allowed_", c("rb","wr","te"))),
      .groups = "drop")

  # -- passing allowed / pressure generated -------------------
  qb <- pbp %>%
    filter(qb_dropback == 1) %>%
    group_by(season, week, game_id, defense = defteam) %>%
    summarise(
      dropbacks_faced = n(),
      attempts_faced = sum(pass_attempt == 1 & sack == 0),
      completions_allowed = sum(complete_pass),
      pass_yds_allowed = sum(passing_yards, na.rm = TRUE),
      pass_td_allowed = sum(pass_touchdown),
      ints_made = sum(interception),
      pass_air_faced = sum(air_yards, na.rm = TRUE),
      sacks_made = sum(sack),
      scrambles_allowed = sum(qb_scramble),
      scramble_yds_allowed = sum(yards_gained[qb_scramble == 1], na.rm = TRUE),
      cpoe_allowed = mean(cpoe, na.rm = TRUE),
      !!!setNames(lapply(DEPTH_LABS, function(b)
        quo(sum(pass_attempt == 1 & sack == 0 & depth_band == !!b,
                na.rm = TRUE))), paste0("att_faced_", DEPTH_LABS)),
      !!!setNames(lapply(DEPTH_LABS, function(b)
        quo(sum(complete_pass[depth_band == !!b], na.rm = TRUE))),
        paste0("cmp_allowed_", DEPTH_LABS)),
      .groups = "drop")

  full_join(ru, rc, by = c("season","week","game_id","defense")) %>%
    full_join(qb, by = c("season","week","game_id","defense")) %>%
    mutate(across(where(is.numeric), \(x) replace_na(x, 0)),
           cpoe_allowed = na_if(cpoe_allowed, 0))
}

.add_def_rates <- function(d) {
  sdiv <- function(a, b) ifelse(b > 0, a / b, NA_real_)
  d <- d %>% mutate(
    ypc_allowed        = sdiv(rush_yds_allowed, carries_faced),
    rush_epa_att_allowed = sdiv(rush_epa_allowed, carries_faced),
    rush_succ_rate_allowed = sdiv(rush_succ_allowed, carries_faced),
    stuff_rate         = sdiv(stuffs_made, carries_faced),
    explosive_rate_allowed = sdiv(explosive_rush_allowed, carries_faced),
    catch_pct_allowed  = sdiv(rec_allowed, targets_faced),
    ypr_allowed        = sdiv(rec_yds_allowed, rec_allowed),
    ypt_allowed        = sdiv(rec_yds_allowed, targets_faced),
    adot_faced         = sdiv(air_yds_faced, targets_faced),
    yac_per_rec_allowed = sdiv(yac_allowed, rec_allowed),
    rec_epa_tgt_allowed = sdiv(rec_epa_allowed, targets_faced),
    comp_pct_allowed   = sdiv(completions_allowed, attempts_faced),
    ypa_allowed        = sdiv(pass_yds_allowed, attempts_faced),
    pass_adot_faced    = sdiv(pass_air_faced, attempts_faced),
    sack_rate          = sdiv(sacks_made, dropbacks_faced),
    scramble_rate_allowed = sdiv(scrambles_allowed, dropbacks_faced),
    int_rate           = sdiv(ints_made, attempts_faced),
    pass_td_rate_allowed = sdiv(pass_td_allowed, attempts_faced)
  )
  for (b in DEPTH_LABS) {
    d[[paste0("comp_pct_allowed_", b)]] <- ifelse(
      d[[paste0("att_faced_", b)]] > 0,
      d[[paste0("cmp_allowed_", b)]] / d[[paste0("att_faced_", b)]], NA_real_)
    d[[paste0("tgt_mix_faced_", b)]] <- ifelse(
      d[["targets_faced"]] > 0,
      d[[paste0("tgt_faced_", b)]] / d[["targets_faced"]], NA_real_)
  }
  for (p in c("rb","wr","te")) {
    d[[paste0("catch_pct_allowed_", p)]] <- ifelse(
      d[[paste0("tgt_faced_", p)]] > 0,
      d[[paste0("rec_allowed_", p)]] / d[[paste0("tgt_faced_", p)]], NA_real_)
    d[[paste0("tgt_share_faced_", p)]] <- ifelse(
      d[["targets_faced"]] > 0,
      d[[paste0("tgt_faced_", p)]] / d[["targets_faced"]], NA_real_)
  }
  d %>% mutate(across(where(is.numeric), \(x) round(x, 4)))
}

aggregate_def_profile <- function(game_tbl, by) {
  cc <- setdiff(names(game_tbl)[sapply(game_tbl, is.numeric)],
                c("season", "week"))
  game_tbl %>%
    group_by(across(all_of(by))) %>%
    summarise(games = n(),
              across(all_of(setdiff(cc, "cpoe_allowed")), sum),
              cpoe_allowed = mean(cpoe_allowed, na.rm = TRUE),
              .groups = "drop") %>%
    .add_def_rates()
}

refresh_defense_profiles <- function(seasons = NULL) {
  if (is.null(seasons)) seasons <- as.integer(gsub("\\D", "", basename(
    list.files(PBP_DIR, pattern = "^play_by_play_\\d{4}\\.csv\\.gz$"))))
  dir.create(DEF_DIR, recursive = TRUE, showWarnings = FALSE)
  g <- build_def_profile_game(seasons)
  write_csv(g %>% .add_def_rates(), DEF_GAME_FILE)
  ss <- aggregate_def_profile(g, c("defense", "season"))
  write_csv(ss, DEF_SEASON_FILE)
  ee <- aggregate_def_profile(g %>% mutate(era = "2021+"), c("defense", "era"))
  write_csv(ee, DEF_ERA_FILE)
  message(sprintf("  defense profiles: %d defense-games, %d defense-seasons, %d era rows",
                  nrow(g), nrow(ss), nrow(ee)))
  invisible(list(game = g, season = ss, era = ee))
}
