# ============================================================
#  game_context.R  (nflmodel)
#
#  Game-level context synced to the play-by-play: one row per
#  game carrying everything the pbp file doesn't (or carries
#  only partially), joined to plays by game_id.
#
#  Source: nflverse nfldata games.csv (Lee Sharpe). Its betting
#  columns are CLOSING numbers (spread_line, total_line,
#  moneylines, spread/total juice) — see nfldata DATASETS.md.
#
#  What lives where:
#    pbp natively:  weather string (condition/temp/humidity/wind),
#                   temp, wind, roof, surface, stadium, coaches,
#                   spread_line, total_line, start_time
#    games.csv adds: closing moneylines + spread/total odds,
#                   rest days, referee, starting QBs, stadium_id,
#                   overtime, division game flag
#    coordinators.csv (generated by scrape_coordinators.R on an
#                   unrestricted network): offensive coordinators
#                   by team-season — joined when present.
#
#  Public API:
#    refresh_game_context()      games.csv -> data/context/game_context.csv
#    load_game_context()         one row per game
#    pbp_with_context(pbp)       plays + posteam-relative context
# ============================================================

library(dplyr)
library(readr)

CONTEXT_DIR       <- file.path("data", "context")
GAME_CONTEXT_FILE <- file.path(CONTEXT_DIR, "game_context.csv")
COORDINATORS_FILE <- file.path(CONTEXT_DIR, "coordinators.csv")

GAMES_CSV_URL <-
  "https://raw.githubusercontent.com/nflverse/nfldata/master/data/games.csv"

# ── Refresh from nflreadr::load_schedules() ──────────────────
#  load_schedules() serves the nfldata games file — the raw URL
#  below is the same dataset, used only where nflreadr isn't
#  installed. Identical columns either way.
refresh_game_context <- function(min_season = 2016) {
  dir.create(CONTEXT_DIR, recursive = TRUE, showWarnings = FALSE)
  raw <- if (requireNamespace("nflreadr", quietly = TRUE)) {
    nflreadr::load_schedules()
  } else {
    read_csv(GAMES_CSV_URL, show_col_types = FALSE, progress = FALSE)
  }
  g <- raw %>%
    filter(season >= min_season) %>%
    transmute(
      game_id, season, game_type, week, gameday, weekday, gametime,
      away_team = normalize_team(away_team),
      home_team = normalize_team(home_team),
      away_score, home_score, result, total, overtime,
      location,                       # "Home" or "Neutral"
      # closing market (nfldata sources closing lines)
      spread_line,                    # points HOME is favored by
      away_spread_odds, home_spread_odds,
      total_line, under_odds, over_odds,
      away_moneyline, home_moneyline,
      # schedule context
      away_rest, home_rest, div_game,
      # environment
      roof, surface, temp, wind, stadium_id, stadium,
      # people
      away_qb_id, home_qb_id, away_qb_name, home_qb_name,
      away_coach, home_coach, referee
    )
  write_csv(g, GAME_CONTEXT_FILE)
  message(sprintf("  game context: %d games (%d-%d) -> %s",
                  nrow(g), min(g$season), max(g$season), GAME_CONTEXT_FILE))
  invisible(g)
}

load_game_context <- function() {
  if (!file.exists(GAME_CONTEXT_FILE)) refresh_game_context()
  read_csv(GAME_CONTEXT_FILE, show_col_types = FALSE)
}

# ── Offensive coordinators (optional layer) ──────────────────
#  Schema: season, team, oc_name, from_week, to_week, source
#  Multiple rows per team-season express mid-season changes.
#  NOTE: no nflverse/R-package dataset publishes coordinators —
#  the schedule data's coach columns are HEAD coaches. Supply
#  this CSV from a source of your choice and the team_oc/opp_oc
#  join activates; absent the file, those columns are NA.
load_coordinators <- function() {
  if (!file.exists(COORDINATORS_FILE)) return(NULL)
  read_csv(COORDINATORS_FILE, show_col_types = FALSE) %>%
    mutate(team = normalize_team(team))
}

# ── Parse the pbp weather string ─────────────────────────────
#  "Sunny Temp: 83° F, Humidity: 72%, Wind: NE 9 mph"
#   -> humidity_pct, wind_dir (condition/temp/wind speed already
#      exist as their own pbp columns)
parse_weather_humidity <- function(weather) {
  suppressWarnings(   # non-matching strings -> NA by design
    as.numeric(sub(".*Humidity:\\s*(\\d+)\\s*%.*", "\\1",
                   ifelse(grepl("Humidity:", weather), weather, NA))))
}
parse_weather_wind_dir <- function(weather) {
  m <- regmatches(weather,
                  regexpr("Wind:\\s*[A-Za-z]+", weather))
  out <- rep(NA_character_, length(weather))
  ok  <- grepl("Wind:\\s*[A-Za-z]+", weather)
  out[ok] <- sub("Wind:\\s*", "", m)
  # "Wind: Calm" etc. — keep only compass-looking directions
  ifelse(out %in% c("N","NE","E","SE","S","SW","W","NW",
                    "NNE","ENE","ESE","SSE","SSW","WSW","WNW","NNW"),
         out, NA_character_)
}

# ── Join context onto plays, posteam-relative ────────────────
#
#  Adds to each play (offense = posteam perspective):
#    is_home        posteam is the home team
#    team_spread    points posteam is favored by (closing)
#    implied_total  posteam's Vegas-implied points
#    team_moneyline / opp_moneyline (closing)
#    team_rest / opp_rest
#    team_coach / opp_coach     (from games.csv, matches pbp's)
#    team_oc / opp_oc           (when coordinators.csv exists)
#    referee, stadium_id, neutral_site
#    humidity_pct, wind_dir     (parsed from pbp weather string)
#
#  spread/total already exist in pbp; the posteam-relative
#  versions here are what the models consume.
pbp_with_context <- function(pbp, ctx = load_game_context()) {
  ctx_j <- ctx %>%
    select(game_id, location, away_spread_odds, home_spread_odds,
           under_odds, over_odds, away_moneyline, home_moneyline,
           away_rest, home_rest, away_qb_name, home_qb_name,
           away_coach, home_coach, referee, stadium_id)

  out <- pbp %>%
    left_join(ctx_j, by = "game_id") %>%
    mutate(
      is_home       = as.integer(posteam == home_team),
      neutral_site  = as.integer(location == "Neutral"),
      team_spread   = ifelse(is_home == 1, spread_line, -spread_line),
      implied_total = total_line / 2 + team_spread / 2,
      team_moneyline = ifelse(is_home == 1, home_moneyline, away_moneyline),
      opp_moneyline  = ifelse(is_home == 1, away_moneyline, home_moneyline),
      team_rest      = ifelse(is_home == 1, home_rest, away_rest),
      opp_rest       = ifelse(is_home == 1, away_rest, home_rest),
      team_coach     = ifelse(is_home == 1, home_coach, away_coach),
      opp_coach      = ifelse(is_home == 1, away_coach, home_coach),
      team_qb_start  = ifelse(is_home == 1, home_qb_name, away_qb_name),
      humidity_pct   = parse_weather_humidity(weather),
      wind_dir       = parse_weather_wind_dir(weather)
    )

  oc <- load_coordinators()
  if (!is.null(oc) && nrow(oc) > 0) {
    oc_j <- oc %>%
      transmute(season, team, oc_name,
                from_week = coalesce(from_week, 1L),
                to_week   = coalesce(to_week, 30L))
    # expand week ranges into a (season, week, team) lookup so the
    # join stays 1:1 even across mid-season coordinator changes
    oc_lookup <- oc_j %>%
      rowwise() %>%
      reframe(season, team, oc_name, week = from_week:to_week)
    out <- out %>%
      left_join(oc_lookup %>% rename(team_oc = oc_name),
                by = c("season", "week", "posteam" = "team")) %>%
      left_join(oc_lookup %>% rename(opp_oc = oc_name),
                by = c("season", "week", "defteam" = "team"))
  } else {
    out <- out %>% mutate(team_oc = NA_character_, opp_oc = NA_character_)
  }
  out
}
